# Generated by Django 4.2.6 on 2023-10-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='partie1',
        ),
        migrations.AddField(
            model_name='post',
            name='image1_partie1',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2_partie2',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3_partie3',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4_partie4',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='partie2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='partie3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='partie4',
            field=models.TextField(blank=True),
        ),
    ]
