# Generated by Django 4.2.6 on 2023-10-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_content_post_partie1_post_image1_partie1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image4_partie4',
            new_name='image1_partie2',
        ),
        migrations.AddField(
            model_name='post',
            name='image1_partie3',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='image1_partie4',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2_partie1',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2_partie3',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2_partie4',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3_partie1',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3_partie2',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3_partie4',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
