# Generated by Django 4.2.6 on 2023-10-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='media')),
                ('default_avatar', models.ImageField(upload_to='media')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('localisation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
