# Generated by Django 4.2.6 on 2023-10-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudo', '0002_blog_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dark_logo',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
